/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShippingImport } from './routes/shipping'
import { Route as ReturnsImport } from './routes/returns'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as FaqImport } from './routes/faq'
import { Route as ContactImport } from './routes/contact'
import { Route as BecomeSellerImport } from './routes/become-seller'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as SellerDashboardImport } from './routes/seller.dashboard'

// Create/Update Routes

const ShippingRoute = ShippingImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRoute,
} as any)

const ReturnsRoute = ReturnsImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const BecomeSellerRoute = BecomeSellerImport.update({
  id: '/become-seller',
  path: '/become-seller',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SellerDashboardRoute = SellerDashboardImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/become-seller': {
      id: '/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof BecomeSellerImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsImport
      parentRoute: typeof rootRoute
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingImport
      parentRoute: typeof rootRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-seller'
    | '/contact'
    | '/faq'
    | '/login'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/seller/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-seller'
    | '/contact'
    | '/faq'
    | '/login'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/seller/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-seller'
    | '/contact'
    | '/faq'
    | '/login'
    | '/register'
    | '/returns'
    | '/shipping'
    | '/seller/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeSellerRoute: typeof BecomeSellerRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeSellerRoute: BecomeSellerRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  SellerDashboardRoute: SellerDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/become-seller",
        "/contact",
        "/faq",
        "/login",
        "/register",
        "/returns",
        "/shipping",
        "/seller/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/become-seller": {
      "filePath": "become-seller.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/returns": {
      "filePath": "returns.tsx"
    },
    "/shipping": {
      "filePath": "shipping.tsx"
    },
    "/seller/dashboard": {
      "filePath": "seller.dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
